[tool.poetry]
name = "mothertongues"
version = "0.1.0"
description = ""
authors = ["roedoejet <hello@aidanpine.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.88.0"
loguru = "^0.6.0"
typer = "^0.7.0"
httpx = "^0.23.1"
gitlint = "^0.19.0"
openpyxl = "^3.1.2"
jsonpath-ng = "^1.5.3"
jsonpointer = "^2.3"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.12.0"
mypy = "^1.4.1"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
