[project]
name = "mothertongues"
version = "1.0.20240222"
description = "Build a dictionary for your language with MotherTongues Dictionaries"
authors = [
  {name = "Aidan Pine", email = "hello@aidanpine.ca"}
]
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
             "fastapi", "loguru", "typer[all]",
             "httpx", "gitlint", "pydantic",
             "openpyxl", "jsonpath-ng", "jsonpointer",
             "nltk", "rank-bm25", "jsf", "questionary"
]

[project.optional-dependencies]
dev = [ "isort", "black", "mypy", "pre-commit"]
docs = [ "mkdocs-material", "mkdocstrings" ]

[project.urls]
Homepage = "https://github.com/MotherTongues/mothertongues"
Documentation = "https://mothertongues.github.io/mothertongues/latest"
Repository = "https://github.com/MotherTongues/mothertongues"
Issues = "https://github.com/MotherTongues/mothertongues/issues"

[project.scripts]
mothertongues = "mothertongues.cli:app"
mtd = "mothertongues.cli:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = "mothertongues"

[tool.mypy]
ignore_missing_imports = true
