name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    # #no-ci in the commit log flags commit we don't want CI-validated
    if: ${{ !contains(github.event.head_commit.message, '#no-ci') }}
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          uv sync
          uv pip install coverage
      - name: Run tests
        run: |
          uv run coverage run mothertongues/tests/run.py dev
          uv run coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false # too many upload errors to keep "true"
